version: 2
jobs:
  build:
    docker:
      - image: registry.opensuse.org/obs/server/unstable/container/sle12/sp3/images/x86_64/openbuildservice/frontend-base:latest
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
  test:
    docker:
      - image: registry.opensuse.org/obs/server/unstable/container/sle12/sp3/images/x86_64/openbuildservice/frontend-base:latest
    steps:
      - checkout
      - run:
          name: rspec
          command: bundle install; bundle exec rspec

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
